name: Run AngelLiveDataFetch-RsiCalculate Notebook

on:
    schedule:
        #- cron: '0 16 * * *' # Every day at 4pm UTC
        - cron: '*/2 * * * *' # Every day at 4pm UTC
    workflow_dispatch:

jobs:
    run-notebook:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.12.1'

            - name: Install dependencies
              run: |
                    
                    pip install notebook nbconvert
                    pip install ta-lib
                    pip install requests
                    pip install numpy
                    pip install pandas
                    pip install requests
                    pip install -r requirements_dev.txt       
                    pip install pyotp
                    pip install logzero
                    pip install websocket-client    
                    pip uninstall pycrypto
                    pip install pycryptodome    
                       

            - name: Run AngelLiveDataFetch-RsiCalculate.ipynb
              env: 
                    ANG_ONE_KEY: ${{ secrets.ANG_ONE_KEY }}
                    CLIENTCODE: ${{ secrets.CLIENTCODE }}
                    PASSWORD: ${{ secrets.PASSWORD }}
                    TOTP_TOKEN: ${{ secrets.TOTP_TOKEN }}
              run: |
                  #  python AngelLiveDataFetch-RsiCalculate.py
                    jupyter nbconvert --to notebook --execute AngelLiveDataFetch-RsiCalculate.ipynb --output executed_notebook.ipynb
